version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: perusable-backend
    command: ["bash", "start.sh"]
    ports:
      - 8003:8000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=perusable
      - SQL_USER=perusable
      - SQL_PASSWORD=perusable
      - SQL_HOST=perusable-database
      - SQL_PORT=5432
      - ES_HOSTS=http://perusable-elasticsearch:9200

  database:
    container_name: perusable-database
    environment:
      - POSTGRES_DB=perusable
      - POSTGRES_USER=perusable
      - POSTGRES_PASSWORD=perusable

    image: postgres:15.2
    ports:
      - "5433:5433"

    volumes:
      - perusable-database:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    command: ["yarn", "start"]
    container_name: perusable-frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app

  elasticsearch:
    container_name: perusable-elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      # WARNING: Enable X-Pack security for production builds
      - xpack.security.enabled=false
    image: elasticsearch:7.17.9
    ports:
      - 9200:9200
    volumes:
      - perusable-elasticsearch:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.9
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'

volumes:
  perusable-database:
  perusable-elasticsearch:
